server:
  port: 80

spring:
  application:
    name: cloud-consumer-order

#eureka配置
eureka:
  client:
    register-with-eureka: true  #true 表示自己要注册到服务中心
    fetch-registry: true        #true 表示自己要去检索下有没有其他的服务可用
    service-url:
      defaultZone: http://localhost:7001/eureka/
